# GitHub Actions Workflow for generating new leads and saving them to a local CSV.
name: 1 - Generate Leads to CSV

# This workflow can be triggered manually from the Actions tab in GitHub.
on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Target Location (e.g., "San Francisco")'
        required: true
        default: 'Surabaya, Indonesia'
      sector:
        description: 'Target Sector (e.g., "Technology")'
        required: true
        default: 'Manufacturing'
      num_companies:
        description: 'Number of new companies to generate'
        required: true
        default: '30'
      workers:
        description: 'Number of parallel workers'
        required: true
        default: '5'

jobs:
  generate-leads:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all history to be able to push back changes.
          fetch-depth: 0

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Create .env file from GitHub Secrets
        run: |
          # This workflow only needs the Gemini API keys.
          echo "GEMINI_API_KEYS=${{ secrets.GEMINI_API_KEYS }}" >> .env

      - name: 5. Run the Lead Generation Script
        id: generate
        run: |
          python leads_generator.py \
            --location "${{ github.event.inputs.location }}" \
            --sector "${{ github.event.inputs.sector }}" \
            --num_companies ${{ github.event.inputs.num_companies }} \
            --workers ${{ github.event.inputs.workers }}

      - name: 6. Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@github.com"

      - name: 7. Commit and Push Updated CSV
        run: |
          # Add the results file to the staging area.
          git add lead_results/lead_results.csv
          
          # Check if there are any changes to commit.
          if git diff-index --quiet HEAD --; then
            echo "No new leads were added to the CSV. Working tree clean."
          else
            echo "New leads detected in CSV. Committing and pushing..."
            git commit -m "feat(data): Update lead results database via GitHub Actions"
            git push
          fi
