# GitHub Actions Workflow for syncing new leads from the CSV to Google Sheets.
name: 2 - Sync CSV to Google Sheets

# This workflow can be triggered manually or scheduled to run periodically.
on:
  workflow_dispatch: # Allows manual runs from the Actions tab.
  # schedule:
  #   - cron: '0 8 * * 1' # Example: Run every Monday at 8:00 AM UTC.

jobs:
  sync-to-sheets:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Create .env file from GitHub Secrets
        run: |
          # This workflow needs the Google Sheets credentials.
          # The GOOGLE_SHEETS_CREDENTIALS_JSON secret must contain the *entire* JSON content.
          echo "GOOGLE_SHEETS_CREDENTIALS_JSON='${{ secrets.GOOGLE_SHEETS_CREDENTIALS_JSON }}'" >> .env
          echo "GOOGLE_SHEETS_SPREADSHEET_ID=${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}" >> .env
          # Optional: Specify the target sheet name. Defaults to 'list_of_leads' in the script.
          # echo "GOOGLE_SHEETS_SHEET_NAME=MyTargetSheet" >> .env

      - name: 5. Run the Sheets Sync Script
        run: python sheets_sync.py
